---
title: ''
output: md_document
---

# Replication package for "Stochastic modelling of football matches using dynamic regressors"

Luiz Fernando G. N. Maia, Teemu Pennanen, Moacyr A.H.B. da Silva and Rodrigo S. Targino


## Structure of the repository

+ `raw-data/` folder of raw data files

+ `data/` folder of processed data files, note that all intermediary data sets, as well as all the outputs, are included in this folder

+ `plots/` folder of generated figures

+ `functions/` functions used during the fitting of models and simulations

+ `simulations/` scripts used to do the simulations presented in Section 7

They need to be ran at this order:
  
1) `matches_to_ignore.R`
2) `models.R`
3) `simulations.R`
4) `probabilities.R`
5) `simulation_studies.R`

+ `eda.Rmd` exploratory data analysis, generates Figures 1 to 6.

+ `param.Rmd` and `stoppage_time_models.Rmd` scripts used to compute the parameters displayed in section 6 (Tables 2, 3, 4, 6, 7, 8).
  
+ `simulation_studies.Rmd` generates Tables 11 (with exception of the last row), 12 and 13.
  
+ `log_lik.Rmd` generates Figure 8.

+ `minute_by_minute.R` generate Figures 9 and 10.

+ `scoring_rules.R` and `scoring_rules_draw.R` generates Figure 7, Tables 9 and 10, and the last row of Table 11.


## Requirements

The analysis were run in R 4.3.1 using the packages `dplyr` (1.1.4), `stringr` (1.5.2), `tidyr` (1.3.1),
`ggplot2` (3.5.2), `ggrepel` (0.9.6), `grid` (4.3.1), `gridExtra` (2.3), `knitr` (1.50), `xtable` (1.8.4),
`future.apply` (1.20.0), `progress` (1.2.3), `CVXR` (1.0.15), `Rmosek` (9.3.2) and `fastDummies` (1.7.5).

For the `Rmosek` and `CVXR` packages, the software `Mosek` (version 9.3) was also used along with its academic license.






